# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('author', models.CharField(max_length=80)),
                ('pub_date', models.IntegerField()),
                ('category', models.CharField(choices=[('OTH', 'Other'), ('PHI', 'Philosophy'), ('FIC', 'Fiction'), ('NON', 'Non-Fiction'), ('PER', 'Performing Arts'), ('VIS', 'Visual Arts'), ('WEB', 'Web Authoring'), ('COM', 'Computer Science')], default='OTH', max_length=3)),
            ],
        ),
    ]
